In [1]:
import numpy as np
from fractions import Fraction
import pandas as pd

In [2]:
alternatives = [
    'Планета Кино',
    'Украина',
    'Баттерфляй Космополит',
    'Киевская Русь',
    'Лейпциг',
    'Мультиплекс'
]

criterions = [
    'Качество изображения',
    'Наличие 3D',
    'Качество акустики',
    'Удобное местоположение',
    'Ценовая политика'
]

In [62]:
def norm(M, method):
    if method == 'av':
        return M.sum(axis=1) / M.sum()
    if method == 'geom':
        return M.prod(axis=1) ** (1 / M.shape[1])
    if method == 'eig':
        return np.linalg.eigh(M.astype(float))[1][:, -1]
    raise NotImplementedError

def hierarchy(alternatives, criterions, Q, Qs, method='av', silent=True, intermediate=False):
    Qnorm = norm(Q, method=method)
    if not silent:
        print('wQ:')
        print(Qnorm.astype(float))
        
    Qsnorm = [norm(q, method=method) for q in Qs]
    if not silent:
        for i in range(len(criterions)):
            print()
            print('wQ%d (%s):' % (i, criterions[i]))
            print(Qsnorm[i].astype(float))
            
    all_norm = np.stack(Qsnorm, axis=1)
    weights = all_norm.dot(Qnorm).astype(float)
    if not silent:
        print()
        print('[A]xB')
        print(weights)
    
    idx = np.argsort(weights)[::-1]
    
    if intermediate:
        return np.array(alternatives)[idx].tolist(), all_norm, weights, np.sort(weights)[::-1]
    return np.array(alternatives)[idx].tolist()

In [63]:
Q = np.array([
    [Fraction(1, 1), Fraction(5, 1), Fraction(3, 1), Fraction(1, 1), Fraction(2, 1)],
    [Fraction(1, 5), Fraction(1, 1), Fraction(1, 3), Fraction(1, 1), Fraction(1, 1)],
    [Fraction(1, 3), Fraction(3, 1), Fraction(1, 1), Fraction(3, 1), Fraction(4, 1)],
    [Fraction(1, 1), Fraction(1, 1), Fraction(1, 3), Fraction(1, 1), Fraction(1, 3)],
    [Fraction(1, 2), Fraction(1, 1), Fraction(1, 4), Fraction(3, 1), Fraction(1, 1)]
])

In [64]:
# Качество изображения
Q1 = np.array([
    [Fraction(1, 1), Fraction(1, 3), Fraction(1, 5), Fraction(5, 1), Fraction(1, 3), Fraction(1, 1)],
    [Fraction(3, 1), Fraction(1, 1), Fraction(1, 3), Fraction(4, 1), Fraction(1, 3), Fraction(3, 1)],
    [Fraction(5, 1), Fraction(3, 1), Fraction(1, 1), Fraction(3, 1), Fraction(2, 1), Fraction(5, 1)],
    [Fraction(1, 5), Fraction(1, 4), Fraction(1, 3), Fraction(1, 1), Fraction(1, 4), Fraction(1, 3)],
    [Fraction(3, 1), Fraction(3, 1), Fraction(1, 2), Fraction(4, 1), Fraction(1, 1), Fraction(4, 1)],
    [Fraction(1, 1), Fraction(1, 3), Fraction(1, 5), Fraction(3, 1), Fraction(1, 4), Fraction(1, 1)]
])

In [82]:
# Наличие 3D
Q2 = np.array([
    [Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(9, 1), Fraction(1, 1)],
    [Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(9, 1), Fraction(1, 1)],
    [Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(9, 1), Fraction(1, 1)],
    [Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(9, 1), Fraction(1, 1)],
    [Fraction(1, 9), Fraction(1, 9), Fraction(1, 9), Fraction(1, 9), Fraction(1, 1), Fraction(1, 9)],
    [Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(1, 1), Fraction(9, 1), Fraction(1, 1)]
])

In [83]:
# Качество акустики
Q3 = np.array([
    [Fraction(1, 1), Fraction(9, 1), Fraction(1, 4), Fraction(2, 1), Fraction(1, 4), Fraction(9, 1)],
    [Fraction(1, 9), Fraction(1, 1), Fraction(1, 6), Fraction(1, 9), Fraction(1, 5), Fraction(3, 1)],
    [Fraction(4, 1), Fraction(6, 1), Fraction(1, 1), Fraction(5, 1), Fraction(1, 1), Fraction(9, 1)],
    [Fraction(1, 2), Fraction(9, 1), Fraction(1, 5), Fraction(1, 1), Fraction(1, 5), Fraction(9, 1)],
    [Fraction(4, 1), Fraction(5, 1), Fraction(1, 1), Fraction(5, 1), Fraction(1, 1), Fraction(9, 1)],
    [Fraction(1, 9), Fraction(1, 3), Fraction(1, 9), Fraction(1, 9), Fraction(1, 9), Fraction(1, 1)]
])

In [84]:
# Удобное местоположение
Q4 = np.array([
    [Fraction(1, 1), Fraction(1, 7), Fraction(2, 1), Fraction(1, 1), Fraction(1, 9), Fraction(3, 1)],
    [Fraction(7, 1), Fraction(1, 1), Fraction(7, 1), Fraction(7, 1), Fraction(1, 2), Fraction(9, 1)],
    [Fraction(1, 2), Fraction(1, 7), Fraction(1, 1), Fraction(1, 1), Fraction(1, 9), Fraction(3, 1)],
    [Fraction(1, 1), Fraction(1, 7), Fraction(1, 1), Fraction(1, 1), Fraction(1, 9), Fraction(3, 1)],
    [Fraction(9, 1), Fraction(2, 1), Fraction(9, 1), Fraction(9, 1), Fraction(1, 1), Fraction(9, 1)],
    [Fraction(1, 3), Fraction(1, 9), Fraction(1, 3), Fraction(1, 3), Fraction(1, 9), Fraction(1, 1)]
])

In [85]:
# Ценовая политика
Q5 = np.array([
    [Fraction(1, 1), Fraction(1, 7), Fraction(1, 7), Fraction(1, 5), Fraction(1, 3), Fraction(1, 9)],
    [Fraction(7, 1), Fraction(1, 1), Fraction(1, 1), Fraction(1, 2), Fraction(1, 2), Fraction(1, 9)],
    [Fraction(7, 1), Fraction(1, 1), Fraction(1, 1), Fraction(2, 1), Fraction(2, 1), Fraction(1, 9)],
    [Fraction(5, 1), Fraction(2, 1), Fraction(1, 2), Fraction(1, 1), Fraction(1, 1), Fraction(1, 9)],
    [Fraction(3, 1), Fraction(2, 1), Fraction(1, 2), Fraction(1, 1), Fraction(1, 1), Fraction(1, 9)],
    [Fraction(9, 1), Fraction(9, 1), Fraction(9, 1), Fraction(9, 1), Fraction(9, 1), Fraction(1, 9)]
])

In [86]:
av_res = hierarchy(alternatives, criterions, Q, [Q1, Q2, Q3, Q4, Q5], method='av', silent=False)
geom_res = hierarchy(alternatives, criterions, Q, [Q1, Q2, Q3, Q4, Q5], method='geom')
eig_res = hierarchy(alternatives, criterions, Q, [Q1, Q2, Q3, Q4, Q5], method='eig')

pd.DataFrame([['По методу строчных сумм'] + av_res] + [['По методу среднего геометрического'] + geom_res] + [['По собственному вектору'] + eig_res], columns=[
    'Метод'] + [('A%i' % i) for i in range(len(alternatives))])

wQ:
[0.33073036 0.09738172 0.31235645 0.1010565  0.15847497]

wQ0 (Качество изображения):
[0.12650764 0.18761726 0.30554811 0.0380595  0.24926293 0.09300456]

wQ1 (Наличие 3D):
[0.19565217 0.19565217 0.19565217 0.19565217 0.02173913 0.19565217]

wQ2 (Качество акустики):
[0.21768478 0.04646192 0.26324671 0.20148498 0.25312184 0.01799978]

wQ3 (Удобное местоположение):
[0.07886109 0.34245039 0.06255393 0.06798965 0.42398619 0.02415876]

wQ4 (Ценовая политика):
[0.02206256 0.11557442 0.14986574 0.10985921 0.08699833 0.51563974]

[A]xB
[0.1403539  0.14853884 0.23240524 0.11885624 0.22025367 0.13959211]

,Метод,A0,A1,A2,A3,A4,A5
0,По методу строчных сумм,Баттерфляй Космополит,Лейпциг,Украина,Планета Кино,Мультиплекс,Киевская Русь
1,По методу среднего геометрического,Лейпциг,Баттерфляй Космополит,Украина,Мультиплекс,Планета Кино,Киевская Русь
2,По собственному вектору,Лейпциг,Планета Кино,Украина,Мультиплекс,Киевская Русь,Баттерфляй Космополит

In [87]:
def IS(M):
    eigenvalues = np.linalg.eigvals(M.astype(float))
    l_max = eigenvalues.max()
    return np.abs(l_max - M.shape[0]) / (M.shape[0] - 1)

In [88]:
Qs = dict(
    Q=Q,
    Q1=Q1,
    Q2=Q2,
    Q3=Q3,
    Q4=Q4,
    Q5=Q5
)
SIs = np.array([0, 0, 0, 0.52, 0.89, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.51, 1.48, 1.56, 1.57, 1.59])

In [89]:
res = list()
for m in Qs.keys():
    M = Qs[m]
    res.append(dict(
        matrix=m,
        shape=M.shape[0],
        l_max=np.abs(np.linalg.eigvals(M.astype(float)).max()),
        IS=IS(M),
        SI=SIs[M.shape[0]],
        OS=IS(M) / SIs[M.shape[0]],
    ))
res = pd.DataFrame(res, columns=['matrix', 'shape', 'l_max', 'IS', 'SI', 'OS'])
res.columns = ['Матрица', 'Размерность', 'Lmax', 'ИС', 'СИ', 'ОС']
res

  Матрица  Размерность      Lmax            ИС    СИ            ОС
0       Q            5  5.802693  2.006732e-01  1.12  1.791725e-01
1      Q1            6  6.600438  1.200876e-01  1.24  9.684481e-02
2      Q2            6  6.000000  1.776357e-16  1.24  1.432546e-16
3      Q3            6  6.862061  1.724121e-01  1.24  1.390420e-01
4      Q4            6  6.249803  4.996058e-02  1.24  4.029079e-02
5      Q5            6  6.479539  9.590780e-02  1.24  7.734500e-02

In [90]:
_, _, weights, _ = hierarchy(alternatives, criterions, Q, [Q1, Q2, Q3, Q4, Q5], method='eig', intermediate=True)
IS_total = res['ИС'][0] + res['ИС'][1:].dot(weights[1:])
SI_total = res['СИ'][0] + res['СИ'][1:].dot(weights[1:])
OS_total = IS_total / SI_total
print('Оценка соглассованости иерархии: %.4f' % float(OS_total))

Оценка соглассованости иерархии: 0.0891

In [91]:
resp1 = (lambda x: [x[e] for e in x.keys()])(np.load('resp1.npz'))
resp2 = (lambda x: [x[e] for e in x.keys()])(np.load('resp2.npz'))
resp3 = (lambda x: [x[e] for e in x.keys()])(np.load('resp3.npz'))

Qa, Qa1, Qa2, Qa3, Qa4, Qa5 = [np.prod(e, axis=0) ** (1 / len(e)) for e in (zip([Q, Q1, Q2, Q3, Q4, Q5], resp1, resp2, resp3))]

hierarchy(alternatives, criterions, Qa, [Qa1, Qa2, Qa3, Qa4, Qa5], method='eig', silent=False)

wQ:
[-0.26119033 -0.47854224 -0.42576104 -0.53277459 -0.48749945]

wQ0 (Качество изображения):
[-0.37302571 -0.38940764 -0.3426105  -0.3438746  -0.41269402 -0.55069543]

wQ1 (Наличие 3D):
[-0.3135266  -0.50492861 -0.32462504 -0.37428659 -0.39573246 -0.49464343]

wQ2 (Качество акустики):
[-0.45025754 -0.19980547 -0.33180398 -0.45034193 -0.66576374 -0.03468192]

wQ3 (Удобное местоположение):
[-0.47136002 -0.25356363 -0.37928378 -0.37226918 -0.65569298 -0.0339324 ]

wQ4 (Ценовая политика):
[-0.4700783  -0.37266128 -0.34100853 -0.32101183 -0.29493752 -0.57777713]

[A]xB
[0.91946011 0.74517298 0.75441678 0.81549536 1.07374108 0.69505466]

['Лейпциг',
 'Планета Кино',
 'Киевская Русь',
 'Баттерфляй Космополит',
 'Украина',
 'Мультиплекс']

In [92]:
_, A, _, w = hierarchy(alternatives, criterions, Q, [Q1, Q2, Q3, Q4, Q5], method='av', intermediate=True)

In [93]:
delta = list()
for c in range(5):
    r1 = list()
    for i in range(Q1.shape[0]):
        r2 = list()
        for j in range(Q1.shape[1]):
            r2.append((w[j] - w[i]) / (A[j, c] - A[i, c] + 1e-8))
        r1.append(r2)
    delta.append(r1)
delta = np.array(delta)

In [94]:
for c in range(delta.shape[0]):
    print()
    print('Критерий %d (%s):' % (c + 1, criterions[c]))
    for i in range(delta.shape[1]):
        for j in range(i):
            print('i=%d(A%d)j=%d(A%d): d=%.4f' % (i + 1, i + 1, j + 1, j + 1, delta[c, i, j]))
            pass

Критерий 1 (Качество изображения):
i=2(A2)j=1(A1): d=-0.1988
i=3(A3)j=1(A1): d=-0.4684
i=3(A3)j=2(A2): d=-0.6081
i=4(A4)j=1(A1): d=1.0407
i=4(A4)j=2(A2): d=0.5342
i=4(A4)j=3(A3): d=0.0306
i=5(A5)j=1(A1): d=-0.7561
i=5(A5)j=2(A2): d=-1.3085
i=5(A5)j=3(A3): d=0.1590
i=5(A5)j=4(A4): d=-0.0036
i=6(A6)j=1(A1): d=3.3892
i=6(A6)j=2(A2): d=1.0717
i=6(A6)j=3(A3): d=0.1397
i=6(A6)j=4(A4): d=-0.3913
i=6(A6)j=5(A5): d=0.1327

Критерий 2 (Наличие 3D):
i=2(A2)j=1(A1): d=1215156.8053
i=3(A3)j=1(A1): d=8386639.8836
i=3(A3)j=2(A2): d=7171483.0783
i=4(A4)j=1(A1): d=9205134.2920
i=4(A4)j=2(A2): d=7989977.4867
i=4(A4)j=3(A3): d=818494.4085
i=5(A5)j=1(A1): d=0.5337
i=5(A5)j=2(A2): d=0.4638
i=5(A5)j=3(A3): d=0.0514
i=5(A5)j=4(A4): d=0.0044
i=6(A6)j=1(A1): d=11354899.7888
i=6(A6)j=2(A2): d=10139742.9835
i=6(A6)j=3(A3): d=2968259.9052
i=6(A6)j=4(A4): d=2149765.4967
i=6(A6)j=5(A5): d=-0.1192

Критерий 3 (Качество акустики):
i=2(A2)j=1(A1): d=0.0710
i=3(A3)j=1(A1): d=-1.8407
i=3(A3)j=2(A2): d=-0.3308
i=4(A4)j=1(A1): d=5.6822
i=4(A4)j=2(A2): d=-0.5154
i=4(A4)j=3(A3): d=0.1325
i=5(A5)j=1(A1): d=-2.6191
i=5(A5)j=2(A2): d=-0.3903
i=5(A5)j=3(A3): d=0.8836
i=5(A5)j=4(A4): d=-0.0148
i=6(A6)j=1(A1): d=0.5686
i=6(A6)j=2(A2): d=3.5625
i=6(A6)j=3(A3): d=0.1210
i=6(A6)j=4(A4): d=0.1172
i=6(A6)j=5(A5): d=0.0882

Критерий 4 (Удобное местоположение):
i=2(A2)j=1(A1): d=-0.0461
i=3(A3)j=1(A1): d=5.1429
i=3(A3)j=2(A2): d=0.2562
i=4(A4)j=1(A1): d=8.4673
i=4(A4)j=2(A2): d=0.2911
i=4(A4)j=3(A3): d=-1.5058
i=5(A5)j=1(A1): d=-0.2689
i=5(A5)j=2(A2): d=-0.9893
i=5(A5)j=3(A3): d=-0.0248
i=5(A5)j=4(A4): d=-0.0021
i=6(A6)j=1(A1): d=2.0758
i=6(A6)j=2(A2): d=0.3186
i=6(A6)j=3(A3): d=0.7731
i=6(A6)j=4(A4): d=0.4905
i=6(A6)j=5(A5): d=0.0519

Критерий 5 (Ценовая политика):
i=2(A2)j=1(A1): d=-0.1299
i=3(A3)j=1(A1): d=-0.6562
i=3(A3)j=2(A2): d=-2.0913
i=4(A4)j=1(A1): d=-1.0485
i=4(A4)j=2(A2): d=13.9802
i=4(A4)j=3(A3): d=0.2046
i=5(A5)j=1(A1): d=-1.4293
i=5(A5)j=2(A2): d=2.8227
i=5(A5)j=3(A3): d=0.1423
i=5(A5)j=4(A4): d=0.0333
i=6(A6)j=1(A1): d=-0.2301
i=6(A6)j=2(A2): d=-0.2535
i=6(A6)j=3(A3): d=-0.0812
i=6(A6)j=4(A4): d=-0.0530
i=6(A6)j=5(A5): d=-0.0484

In [95]:
res = list()
for i in range(len(alternatives)):
    for j in range(i + 1, len(alternatives)):
        d = dict()
        d['Пара']=(i + 1, j + 1)
        
        for c in range(len(criterions)):
            d['C%d' % (c + 1)] = delta[c, i, j]
        res.append(d)

df = pd.DataFrame(res)
df

          C1            C2        C3        C4         C5    Пара
0  -0.198849 -1.215157e+06  0.070969 -0.046100  -0.129947  (1, 2)
1  -0.468421 -8.386640e+06 -1.840712  5.142921  -0.656215  (1, 3)
2   1.040738 -9.205134e+06  5.682256  8.467270  -1.048461  (1, 4)
3  -0.756082  5.336755e-01 -2.619097 -0.268926  -1.429306  (1, 5)
4   3.389212 -1.135490e+07  0.568641  2.075762  -0.230053  (1, 6)
5  -0.608109 -7.171483e+06 -0.330811  0.256219  -2.091340  (2, 3)
6   0.534240 -7.989977e+06 -0.515406  0.291116  13.980202  (2, 4)
7  -1.308471  4.638040e-01 -0.390311 -0.989278   2.822695  (2, 5)
8   1.071711 -1.013974e+07  3.562538  0.318568  -0.253452  (2, 6)
9   0.030599 -8.184944e+05  0.132525 -1.505767   0.204590  (3, 4)
10  0.158954  5.144370e-02  0.883640 -0.024754   0.142311  (3, 5)
11  0.139654 -2.968260e+06  0.121031  0.773082  -0.081150  (3, 6)
12 -0.003607  4.380265e-03 -0.014753 -0.002140   0.033323  (4, 5)
13 -0.391257 -2.149765e+06  0.117163  0.490468  -0.052979  (4, 6)
14  0.132702 -1.192312e-01  0.088192  0.051862  -0.048376  (5, 6)

In [96]:
df.where(df < 1).fillna('-')

            C1            C2         C3          C4         C5    Пара
0    -0.198849 -1.215157e+06  0.0709693  -0.0461004  -0.129947  (1, 2)
1    -0.468421 -8.386640e+06   -1.84071           -  -0.656215  (1, 3)
2            - -9.205134e+06          -           -   -1.04846  (1, 4)
3    -0.756082  5.336755e-01    -2.6191   -0.268926   -1.42931  (1, 5)
4            - -1.135490e+07   0.568641           -  -0.230053  (1, 6)
5    -0.608109 -7.171483e+06  -0.330811    0.256219   -2.09134  (2, 3)
6      0.53424 -7.989977e+06  -0.515406    0.291116          -  (2, 4)
7     -1.30847  4.638040e-01  -0.390311   -0.989278          -  (2, 5)
8            - -1.013974e+07          -    0.318568  -0.253452  (2, 6)
9    0.0305992 -8.184944e+05   0.132525    -1.50577    0.20459  (3, 4)
10    0.158954  5.144370e-02    0.88364  -0.0247535   0.142311  (3, 5)
11    0.139654 -2.968260e+06   0.121031    0.773082 -0.0811501  (3, 6)
12 -0.00360688  4.380265e-03 -0.0147527 -0.00213987  0.0333227  (4, 5)
13   -0.391257 -2.149765e+06   0.117163    0.490468 -0.0529785  (4, 6)
14    0.132702 -1.192312e-01  0.0881919    0.051862 -0.0483758  (5, 6)

In [97]:
np.abs(df.where(df < 1)[['C1', 'C2', 'C3', 'C4', 'C5']]).max(axis=0)

C1    1.308471e+00
C2    1.135490e+07
C3    2.619097e+00
C4    1.505767e+00
C5    2.091340e+00
dtype: float64